[package]
name = "ddcore-rs"
version = "0.3.5"
edition = "2021"
license = "MIT"
description = "Core features for interacting with the game Devil Daggers"
repository = "https://github.com/lsaa/ddcore-rs"
homepage = "https://github.com/lsaa/ddcore-rs"
documentation = "https://docs.rs/ddcore-rs"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
memory = ["serde_json", "process-memory", "sysinfo", "winapi", "scan_fmt"]
ddinfo = ["serde_json", "hyper", "hyper-rustls", "rustls", "futures", "base64"]
ddreplay = ["serde_json", "hyper", "hyper-rustls", "rustls", "futures", "base64"]
ddcl_submit = ["aes", "cbc", "pbkdf2", "ring", "base32", "base64"]
logger = []

[dependencies]
anyhow = "1.0"
num-traits = "0.2"
num-derive = "0.3"
bytestream = "0.4"
libflate = "1.1"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = { version = "1.0", optional = true }
process-memory = { version = "0.4", optional = true }
sysinfo = { version = "0.28", optional = true }
scan_fmt = {version = "0.2", optional = true }
hyper = { version = "0.14", optional = true, features = ["full"] }
hyper-rustls = { version = "0.23", optional = true }
rustls = { version = "0.20", optional = true }
aes = { version = "0.8", optional = true }
cbc = { version = "0.1", optional = true }
pbkdf2 = { version = "0.10", default-features = false, optional = true }
ring = { version = "0.16", optional = true }
base32 = { version = "0.4", optional = true }
base64 = { version = "0.13", optional = true }
futures = { version = "0.3", optional = true }
log = "0.4"
md5 = "0.7"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["tlhelp32", "winuser"], optional = true }

